### ISSUE TITLE
Exit code is 0 on wrapper error during service start

### ISSUE THREAD

**Issue by mpanar** [winsw/winsw#198]
In this scenario the service user is Network Service; when starting the service, a System.UnauthorizedAccessException is thrown when attempting to write to the wrapper log file, as this user has no write permissions on the current directory.

In the console the output is as follows:

`2017-03-06 11:43:04,715 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-06 11:43:05,177 INFO  - Completed. Exit code is 0`

In the Event logs though we can see the error occurring:

`An unhandled exception ('System.UnauthorizedAccessException') occurred in process #12528. Just-In-Time debugging this exception failed with the following error: The process ID is invalid.`

In this case the service errors and stops, but the java process is left running, and the exit code is 0, the error only logged to the event registry.

Fixing the folder permissions gets rid of this specific problem, but I have seen similar behaviour on other occasions, and that makes it tricky to detect when something goes wrong.

**Comment by oleg-nenashev** [comment]
Yes, I also noticed that. IIRC I have created a bug for it, but seems I've actually forgotten to do that.
It actually applies to all commands, which invoke service operation and then do not wait for the startup result

**Comment by fuweichin** [comment]
*I just want to raise a new issue, but now that here is an similar one so I put the issue here.*

# Proposal to make winsw.exe exit more useful code

**Overview**:  
Exit code of `winsw.exe` always kept to be 0, while `net start` and `net stop` exit useful code.

**Steps to Reproduce**:  
```
C:\Library\nginx-1.14.0>nginx-winsw.exe status
Stopped

C:\Library\nginx-1.14.0>echo %ERRORLEVEL%
0

C:\Library\nginx-1.14.0>nginx-winsw.exe start
2019-01-29 23:54:30,059 INFO  - Starting the service with id 'nginx'

C:\Library\nginx-1.14.0>nginx-winsw.exe status
Started

C:\Library\nginx-1.14.0>echo %ERRORLEVEL%
0
```
**Actual Result:**  
`winsw.exe status` indicates service is stopped, but its exit code is 0.

**Expected Result:**  
expect exit code of `winsw.exe status` not to be 0 if a service is stopped.

just like a typical SystemV script does  
```
root@qin-workstation:~# service nginx status
[FAIL] nginx is not running ... failed!
root@qin-workstation:~# echo $?
3
root@qin-workstation:~# service nginx start
root@qin-workstation:~# service nginx status
[ ok ] nginx is running.
root@qin-workstation:~# echo $?
0
```

also, if failed to start a service, winsw.exe should exit a code other that 0  
```
C:\Library\nginx-1.14.0>nginx-winsw.exe start
2019-01-29 23:57:02,197 INFO  - Starting the service with id 'nginx'

C:\Library\nginx-1.14.0>echo %ERRORLEVEL%
0

C:\Library\nginx-1.14.0>nginx-winsw.exe status
Stopped
```

for more expectations, see table below  

| op \ exit code \ type | actual             | expected           |
|:------------------ |:------------------ |:------------------ |
| started/stopped/restarted | 0                  | 0           |
| failed to start/stop/restart | 0                  | non-zero           |
| status started  | 0                  | 0           |
| status stopped  | 0                  | non-zero           |
| status non-existent  | 0                  | non-zero           |

**Additional Information**
winsw-v2.2.0 WinSW.NET4.exe
Windows 10
