### ISSUE TITLE
Changing Assembly Information for created services

### ISSUE THREAD

**Issue by aminjam** [winsw/winsw#199]
When I create a new service, I would like to change the default Assembly information for the newly created services in winsw.

```
[assembly: AssemblyTitle("Windows Service Wrapper for .NET4")]
[assembly: AssemblyDescription("Allows arbitrary process to run as a Windows service by wrapping it")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("CloudBees, Inc.")]
[assembly: AssemblyProduct("Windows Service Wrapper")]
[assembly: AssemblyCopyright("Copyright 2008-2016 Oleg Nenashev, CloudBees, Inc. and other contributors")]
```

I would hope to add a new XML configuration with the appropriate fields. Would that be possible? If so, I would be happy to send a PR for this feature. If you have any input as to how to make this feature happen, I would like to hear your thoughts.

**Comment by oleg-nenashev** [comment]
In order to change the assembly information, you would have to rebuild the binary. And obviously it causes some legal issues with the copyrights, etc.

Why would you want to change this information?

**Comment by aminjam** [comment]
All services created with winsw have "CloudBees, Inc." as the manufacturer. This is confusing for our product consumers. We would ideally like to not have that. How can we accomplish this?

**Comment by oleg-nenashev** [comment]
Agreed, it needs to become customizable somehow. I definitely do not want CloudBees to appear as a vendor in any service powered by WinSW (CC @hrmpw). I will check if there is a way to do that without Executable patching. Hopefully there is API, which can be invoked during the service installation.

**Comment by oleg-nenashev** [comment]
Hello. Sorry for the late response. This summer I have a discussion with @kohsuke and other CloudBees representatives about the current `AssemblyCompany` field. Since it is a trademark-related question, I need @kohsuke's approval to change this field in the **.NET2** package. His decision was to keep the current field value.

**.NET4** package has been created by me, so I could change the `AssemblyCompany` in this package to something neutral like "WinSW contributors". But it still does not really address the use-case when projects/vendors want to have their name in assembly info.

For this purpose WinSW can be repackaged or modified with tools like [mt.exe](https://msdn.microsoft.com/en-us/library/windows/desktop/aa375649(v=vs.85).aspx).

**Comment by NextTurn** [comment]
If we offer "customization" for the product, there may not be copyright issues.

https://wrapper.tanukisoftware.com/doc/english/customize.html#manufacturer

**Comment by NextTurn** [comment]
https://github.com/winsw/winsw/issues/137#issuecomment-660575115_ also applies here.
