### ISSUE TITLE
Support for Windows Server 2016 Nano

### ISSUE THREAD

**Issue by spawluk** [winsw/winsw#219]
Hi. 

I'm using WinSW to host Consul, becase it have nice config for shutdown command.
I want to migrate my Consul servers to WS16 nano, but i receive error

```
 .\winsw.exe status
Program 'winsw.exe' failed to run: The subsystem needed to support the image type is not present.
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by oleg-nenashev** [comment]
@spawluk My first guess is that it is due to the missing WoW64 support. Could you please check your system according to this guide? https://support.microsoft.com/en-us/help/974727/message-subsystem-needed-to-support-the-image-type-is-not-present-error-when-installing-or-running-applications-on-windows-server-2008-r2-core

**Comment by spawluk** [comment]
I'm unable to run it on Nano Server:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/213c7070-ea67-4dac-a023-e663db0c66ab/nano-server-wow64-program-setupexe-failed-to-run-the-subsystem-needed-to-support-the-image?forum=windowscontainers

**Comment by oleg-nenashev** [comment]
So yes, it is WoW64. Windows Server Nano has no 32bit subsystem. And probably other subsystems required for WinSW. 

Unfortunately I have no proper test environment to test it in short-term. I can probably run it on AWS, but I will unlikely be able to dedicate time for fixing till late June.

**Comment by oleg-nenashev** [comment]
Created a follow-up ticket in Jenkins: https://issues.jenkins-ci.org/browse/JENKINS-44448
Let's see if I can get some resources/eng.time there

**Comment by oleg-nenashev** [comment]
After the recent updates by @NextTurn the service still depends on Advapi32, and IIUC it still won't work on Nano servers. I wonder whether we could have a special .NET Core bundle or other packaging would include reverse forwarder DLLs or just use lower level APIs.

**Comment by NextTurn** [comment]
Why do we have to do with 32-bit subsystem? Doesn't the program run in 64-bit mode? https://github.com/kohsuke/winsw/pull/359#issuecomment-576320241

**Comment by NextTurn** [comment]
It turned out that Nano Server doesn't support full .NET Framework. .NET Core bundles could resolve this issue.

**Comment by NextTurn** [comment]
#### Nano Server checklist

- [x] .NET Core is not included by default: .NET Core self-contained bundles.
- [ ] WMI is not included by default.
- [x] Reverse forwarders are included by default since TP5.

For more information, see [Changes to Nano Server in Windows Server Semi-Annual Channel](https://docs.microsoft.com/en-us/windows-server/get-started/nano-in-semi-annual-channel).

**Comment by NextTurn** [comment]
This issue can already be worked around by using .NET Core bundles and installing reverse forwarders on older platforms.

We're not going to use "low level" APIs. For reference, see dotnet/corefx# 13440.
