### ISSUE TITLE
When windows service switches to the RUNNING state when executing a java application

### ISSUE THREAD

**Issue by jan-krakora** [winsw/winsw#248]
Can anybody tell me what is the point within a java application when the windows service switches to the RUNNING state? Is it right after the main method has been called or when? 

I'm asking because we have a service wrapper running a java application. The service is set to automatically start upon windows startup and sometimes it fails because the "30s service starting limit" is reached.

Thank you.

**Comment by oleg-nenashev** [comment]
@jan-krakora WinSW invokes [WMI](https://msdn.microsoft.com/en-us/library/aa394582(v=vs.85).aspx) call to start the service and exits when it finishes. It does not really check the executable status if it is running. So the issue may happen if WMI service does not handle the request quickly due to whatever reason.

Other case - extra initialization operations like `download` in WinSW initialization logic. They happen before the executable start and contribute to the overall timeout

**Comment by NextTurn** [comment]
The answer was in https://github.com/winsw/winsw/issues/267#issuecomment-369881876. To summarize, the service is designed to switch to the "RUNNING" state right after your Java process is created.

If the timeout problem persists, please check the logs (especially the Event Log for 2.x) and send a bug report. Thanks.
