### ISSUE TITLE
Java ShutDownHook not run

### ISSUE THREAD

**Issue by lafual** [winsw/winsw#283]
Even with "stoptimeout" set, the ShutDownHook is never run when the service is stopped. The ShutDownHook does run if the Java application throws an uncaught exception.

Log is

`2018-07-01 19:33:23,134 INFO  - Stopping DRS IDB DEV Test
2018-07-01 19:33:23,149 DEBUG - ProcessKill 8732
2018-07-01 19:33:23,250 INFO  - Found child process: 7420 Name: conhost.exe
2018-07-01 19:33:23,290 INFO  - Stopping process 7420
2018-07-01 19:33:23,309 INFO  - Send SIGINT 7420
2018-07-01 19:33:23,314 WARN  - SIGINT to 7420 failed - Killing as fallback
2018-07-01 19:33:23,324 INFO  - Stopping process 8732
2018-07-01 19:33:23,334 INFO  - Send SIGINT 8732
2018-07-01 19:33:23,339 WARN  - SIGINT to 8732 failed - Killing as fallback
2018-07-01 19:33:23,344 INFO  - Finished DRS IDB DEV Test
2018-07-01 19:33:23,354 DEBUG - Completed. Exit code is 0`

Code is

**Comment by oleg-nenashev** [comment]
@lafual What is "ShutDownHook"? Is it a part of your Java application?

**Comment by oleg-nenashev** [comment]
I'd guess it is https://docs.oracle.com/javase/8/docs/technotes/guides/lang/hook-design.html . Then it should be invoked according to http://blog.nidi.guru/java/tech/2015/05/07/shutdown-hooks/

I need source codes for the reproducible scenario in order to proceed. It would be also nice to know which JVM version is used.

**Comment by lafual** [comment]
Java 8 on Windows 10. 
If run within CMD, [Ctrl][C] causes the ShutDownHook to run. Google says [Ctrl][C] sends SIGINT. Given the error in my original post, it looks like something is blocking it before getting to the Java process.

Java source code attached.

[ServiceTest - Copy.txt](https://github.com/kohsuke/winsw/files/2153044/ServiceTest.-.Copy.txt)

XML configuration attached.

[WinSW.NET4 - Copy.txt](https://github.com/kohsuke/winsw/files/2153051/WinSW.NET4.-.Copy.txt)

**Comment by lafual** [comment]
Closed by mistake.

**Comment by izhuravlova** [comment]
Hi Oleg, 

Thanks for the winsw, I like the product a lot. 
I am observing unexpected behavior on Windows 10 with ShutdownHook (Java 8, Spring) not being notified of the Service Stop.  The same installation works well on Windows 7. Looks like Lafual had similar issue, do you have any recommendations of possible solution to the problem?

Thanks lot, 
~Irene

**Comment by ryanrupp** [comment]
Possibly related a bit to https://github.com/kohsuke/winsw/issues/95

On Windows 8 (just VM I had available, could try other versions from free dev VM downloads Microsoft provides) - I tried setting:
```
<stopparentprocessfirst>true</stopparentprocessfirst>
```
While it does report the `SIGINT` didn't fail in this case, the shutdown hooks don't end up running still. Different variations I've tried so far:

1. Enabling/disabling `-Xrs` passed to java launch
2. Trying to use `javaw` instead of `java` (no console this case)

I grabbed the `sendctrlc` executable from `winp` here - https://github.com/kohsuke/winp/blob/master/native/sendctrlc/main.cpp#L17 - which is basically doing the same thing this code appears to be doing. My results here are:

1. When launching via winsw and calling `sendctrlc` the process cannot be interrupted and it ends with error code 5 (ERROR_ACCESS_DENIED)
2. When launching the Java app just from command line and using `sendctrlc` it interrupts correctly (and runs shutdown hooks)

The documentation states:
```
If the calling process is already attached to a console, the error code returned is ERROR_ACCESS_DENIED (5)
```
So, I tried with `javaw` but it failed the same way. Not sure what's going on as I'm not really familiar with the quirks of these APIs. I did end up finding `winp` in the first place because I was looking at how IntelliJ handles this as I believe it works correctly (although I use OSX primarily so need to verify that!). IntelliJ does delegate its graceful install to the `winp` library though which then does the same thing essentially that the `winsw` C# code is doing.

**Comment by ryanrupp** [comment]
I spent some more time looking at this. Given interrupt works when running the Java application from the command line but it doesn't when running as a Windows service, I feel like this must be isolated to some protections/differences of launching the application as a sub process of a Windows service. The weird thing though is:
1) I couldn't find much information online that report this being an issue, most just suggest the same approach taken here
2) I did find an "Azure Pipelines Agent" that does this exact same thing basically for a clean shutdown, see here - https://github.com/microsoft/azure-pipelines-agent/pull/161/files . This makes me think this *should* work so I'm not sure what other variables I'm missing here. Maybe some combination of windows service + java makes it happen. For example someone here - https://github.com/kohsuke/winsw/issues/95#issuecomment-466060692 - mentioned that SIGINT works correctly for Nginx. I barely have a Windows environment setup so this was hard for me to test but it would be good to just create a dummy C or Go based executable that just does a sleep and verify interrupt works correctly.
