### ISSUE TITLE
user home directory changed in winsw service

### ISSUE THREAD

**Issue by rookiebulls** [winsw/winsw#340]
I need to use my home directory in my program, it works fine when I test it. But it failed when it run as a service created by winsw.  It's because my home direcotry is changed to `C:\WINDOWS\system32\config\systemprofile` in winsw service, how's that happening?

**Comment by thecoshman** [comment]
@rookiebulls Sounds like you've set up the service to run as 'the system', rather than as you. This wouldn't be an issue with winsw, but how the service is configured. You should update the configuration of your Windows service such that it explicitly runs with your credentials. You can, I believe, put these details into the config file, but I would be keen on putting my credentials into a plain text file like that.

**Comment by NextTurn** [comment]
A service is installed as the `LocalSystem` account by default. You can change this with the `<serviceaccount>` setting. The documentation issue is tracked by #444.

There is a `/p` option which allows prompting for username and password. More is to come in #308.

I'm closing this in favor of the issues mentioned above. Feel free to file a new issue if further action is required. Thanks.
