### ISSUE TITLE
Proposal: Add command line options

### ISSUE THREAD

**Issue by NextTurn** [winsw/winsw#433]
Add options to modify existing commands instead of adding new commands with similar names (`stopwait` => `stop -wait`) or appending exclamation marks (`stop!` => `stop -force`).

.NET Core projects have widely adopted all kinds of option styles with dashes. (No one use slashes nowadays.)

- `value`
- `-anoption value`
- `--an-option value`

Need to carefully think about this because this step is irreversible.

**Comment by dreamflow** [comment]
> Add options to modify existing commands instead of adding new commands with similar names

i support your proposal ^ , it's better for future additions of options ,
than many single-word commands .

 > stop! => stop -force

i prefer the words over short symbols , because words are self descriptive ,
but short symbols like "!" have multiple/different meanings in different
tools and programming-languages .
so then i come back to a service after a while and read it's command-line ,
a word is obvious in its meaning , while short symbols i have to look up
more in the documentation , because of the different meanings in
different tools and programming languages .
