### ISSUE TITLE
Define a milestone management policy

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#453]
I noticed that @NextTurn has created a bunch of historical milestones while I was doing a cleanup of existing ones. I am not against it, but we need to somehow document the desired process to follow it consistently

**Comment by NextTurn** [comment]
The linked milestone is simply the next release version after the issue is closed.

@oleg-nenashev Would you like to grant access to a new *winsw-bot* account which will do such automations? A GitHub app is OK as well.

**Comment by oleg-nenashev** [comment]
GitHub App or Github Action would be my preference

**Comment by NextTurn** [comment]
Proposed workflow:

- Place unplanned issues in "Future".
- Place planned/WIP/done issues in "*.x".
- When new version is released, create a corresponding milestone and move closed issues there.

**Comment by oleg-nenashev** [comment]
Fine with me. Do we have special benefits in using milestones on their own? Or does it just address lack of automated "pull request => release" in GithHub?

**Comment by NextTurn** [comment]
For historical issues, it helped to associate *issues* with release versions because a bunch of them were not *linked* with pull requests or commits. PR versions can be easily determined by checking the tags containing the merge commit.

![image](https://user-images.githubusercontent.com/45985406/78103224-f0710100-741e-11ea-93ad-141ebbc1a55d.png)

For open issues, it groups changes into major and minor ones.

In the future, we could consider abandon the workflow instead.
