### ISSUE TITLE
how to start winform base exe 

### ISSUE THREAD

**Issue by rqx110** [winsw/winsw#58]
I have a winform application want to start as service. but it can't do it with winsw

**Comment by oleg-nenashev** [comment]
@Trinition 
Under which credentials do you start the service?
In order to show GUI windows from the service, you should use the current user at least. There're also many other requirements (e.g. support of such run type by *your application*), so most probable your application won't work as you want

**Comment by oleg-nenashev** [comment]
@rqx110 
If I understand correctly, the response above applies to your case as well

**Comment by Trinition** [comment]
I have a dedicated account created in our Windows Domain for the services
I'm running. All services are set to log on as that user.

While I did not personally create that account, I believe it was created
with the necessary rights to do what it needs. Perhaps that includes
interacting with the desktop? I could check later when I get to work if
anyone is curious.

**Comment by NextTurn** [comment]
Not sure if the problem persists. I often use *notepad.exe* with the LocalSystem account for testing, and it works fine.

Or do you want to see the GUI?
