### ISSUE TITLE
waitFor feature

### ISSUE THREAD

**Issue by treaz** [winsw/winsw#93]
Hello,

great work on the service wrapper. Thank you :+1: 
Does it offer any mechanism that would actually keep the windows service in status starting until some trigger/callback event?

I'm wrapping a java application that starts up quite slowly and the wrapper returns the status started for the service before the application is fully initialized.

**Comment by kenny-evitt** [comment]
I'm not sure you want to do this. Depending on how long your Java application takes to start, Windows may cancel starting the service if it exceeds its timeout. I expect the wrapper now returns a started status immediately because of that. See my older issue – #52 – for an example of problems that might be due to the service not finishing 'starting' immediately.

**Comment by treaz** [comment]
I wonder if keeping the service in a starting state until everything is ready is something easy to do.
Something like this: https://www.devopsonwindows.com/avoid-windows-service-start-up-timeouts/

**Comment by oleg-nenashev** [comment]
WinSW 2 offers an extension engine, so it likely could be implemented as an extension. But I have no plan to work on it in short-term. BTW, somebody could create a pull request

**Comment by NextTurn** [comment]
> I wonder if keeping the service in a starting state until everything is ready is something easy to do.
> Something like this: https://www.devopsonwindows.com/avoid-windows-service-start-up-timeouts/

This is exactly what we do.

See my questions in #267 to complete a feature request.

According to #95, the author no longer works on Windows, so closing this as a dup.

Duplicate of #267
