### ISSUE TITLE
Create folder if specified logpath folder does not exist

### ISSUE THREAD

**Issue by cwb124** [winsw/winsw#99]
Would be awesome if the software could check for and create the folder location specified in the <logpath> if it doesn't exist.  As of now, if it doesn't exist, the service installs successfully but fails to start.  Putting that check in would improve this software's support for being part of new deployments.

**Comment by oleg-nenashev** [comment]
Actually it tries to create the directory if it does not exist: https://github.com/kohsuke/winsw/blob/12c16e40a7008b6c59fb6513f1b1306f2f393605/src/Core/ServiceWrapper/Main.cs#L162-L165 . But there may be missing logging if the directory does not exist and cannot be created. It has been fixed by #143 (see https://github.com/kohsuke/winsw/pull/143/commits/871afa0f2c1e5fe6742c108ce3c696864cef1eea). Now there will be errors in all available channels

**Comment by oleg-nenashev** [comment]
Closing it since we have diagnostics in place
